services:

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: hybrid-rag-backend
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: hybrid-rag-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hybrid-rag.rule=Host(`jissantechnologies.online`)"
      - "traefik.http.routers.hybrid-rag.entrypoints=websecure"
      - "traefik.http.routers.hybrid-rag.tls.certresolver=letsencrypt"
      - "traefik.http.routers.hybrid-rag.tls=true"
      - "traefik.http.services.hybrid-rag.loadbalancer.server.port=8501"