services:

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: hybrid-rag-backend
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: hybrid-rag-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend